export const TREND_MOVIES_URL    = '/movie/popular'
export const MOVIES_URL          = '/trending/movie/day'
export const GENRE_URL           = '/genre/movie/list'
export const UPCOMING_MOVIES_URL = '/tv/popular'
export const OLD_MOVIES_URL      = '/movie/top_rated'
export const TVSHOWS_URL         = '/trending/tv/day'
export const SERIES_URL          = '/trending/tv/day'